include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_NAME "solver")
set(CPACK_PACKAGE_VENDOR "dp apps")
set(CPACK_PACKAGE_CONTACT ${GITHUB_EMAIL})
set(CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "solver app for quadratic equations")
set(CPACK_PACKAGE_VERSION_MAJOR ${PVERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PVERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PVERSION_PATCH})
set(CPACK_PACKAGE_VERSION_TWEAK ${PVERSION_TWEAK})

set(CPACK_GENERATOR "ZIP;TGZ")

set(CPACK_DEBIAN_PACKAGE_MAINTAINER "dp229")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>= 2.43)")

include(CPack)
